name: 'ManyVM'
description: 'Run many different VMs in different CPU architectures'
inputs:
  os:
    description: 'OS name'
    required: true
  version:
    description: 'OS version'
    required: true
    default: 'latest'
  arch:
    description: 'CPU architecture'
    required: false
    default: 'x86_64'
  cpu:
    description: 'Specify which CPU to emulate'
    required: false
    default: 'auto'
  bios:
    description: 'Specify which BIOS to use'
    required: false
    default: 'auto'
  machine:
    description: 'Specify which machine to emulate'
    required: false
    default: 'auto'
  os_image_url:
    description: 'OS Image URL'
    required: false
  run:
    description: 'Run commands in VM'
    required: true
runs:
  using: 'node20'
  main: 'dist/index.js'
